-- Monitors
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@90",
    position = "0x0",
    scale = "1.5",
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})

-- Autostart

-- Env vars
hl.env("XCURSOR_SIZE", "24")
hl.env("_JAVA_AWT_WM_NONREPARENTING", "1")
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("XDG_CONFIG_HOME", "$HOME/.config")
hl.env("XDG_CACHE_HOME", "$HOME/.cache")
hl.env("XDG_DATA_HOME", "$HOME/.local/share")
hl.env("XDG_STATE_HOME", "$HOME/.local/state")
hl.env("GTK_THEME", "Adwaita:dark")

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

hl.window_rule({
    name = "windowrule-1",
    match = {
        class = "^(firefox)$",
        title = "^(Picture-in-Picture)$",
    },
    float = true,
    move = "(0) ((monitor_h*0.8))",
    size = "(monitor_w*0.2) (monitor_h*0.2)",
})

hl.window_rule({
    name = "windowrule-2",
    match = {
        class = "^(firefox)$",
        title = "^(Firefox — Sharing Indicator)$",
    },
    float = true,
    move = "(0) (0)",
})

hl.window_rule({
    name = "windowrule-3",
    match = {
        class = "^(pavucontrol)$",
    },
    float = true,
    move = "((monitor_w*0.7)) (24)",
    size = "(monitor_w*0.3) (monitor_h*0.4)",
})

hl.window_rule({
    name = "windowrule-4",
    match = {
        class = "^(com.nextcloud.desktopclient.nextcloud)$",
        title = "^(Nextcloud)$",
    },
    float = true,
    move = "((monitor_w*0.7)) (24)",
    size = "(monitor_w*0.3) (monitor_h*0.4)",
})

hl.window_rule({
    name = "windowrule-5",
    match = {
        class = "^(org\\.keepassxc\\.KeePassXC)$",
        title = "^(Generate Password)$",
    },
    float = true,
})

hl.workspace_rule({
    workspace = "w[tv1]",
    gaps_out = 0,
    gaps_in = 0,
})

hl.workspace_rule({
    workspace = "f[1]",
    gaps_out = 0,
    gaps_in = 0,
})

hl.window_rule({
    name = "windowrule-6",
    match = {
        float = 0,
        workspace = "w[tv1]",
    },
    border_size = 0,
    rounding = 0,
})

hl.window_rule({
    name = "windowrule-7",
    match = {
        float = 0,
        workspace = "f[1]",
    },
    border_size = 0,
    rounding = 0,
})

local mainMod = "SUPER"

hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("alacritty"))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("alacritty -e ranger"))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("pkill bemenu-run || bemenu-run -i -p \">\" -H 24 -fn \"FiraCode Nerd Font\""))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("swaylock"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exit())
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("kitty halt -p;,"))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("killall -SIGUSR1 waybar"))
hl.bind(mainMod .. " + F11", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F11", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + ALT + 1", hl.dsp.focus({ monitor = 1 }))
hl.bind(mainMod .. " + ALT + 2", hl.dsp.focus({ monitor = 2 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + ALT + right", function() local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "+1" })) end)
hl.bind(mainMod .. " + ALT + left", function() local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = -1 })) end)

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))

hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.resize({ x = 20, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.resize({ x = -20, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.resize({ x = 0, y = -20, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.resize({ x = 0, y = 20, relative = true }), { repeating = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("light -A 10"), { repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("light -U 10"), { repeating = true })

hl.device({
    name = "ydotoold-virtual-device",
    kb_layout = "us",
    kb_variant = "",
    kb_options = "",
})

hl.config({
    input = {
        kb_layout = "de",
        kb_variant = "nodeadkeys",
        kb_model = "latin1",
        kb_options = "",
        kb_rules = "",
        numlock_by_default = true,
        follow_mouse = 2,
        touchpad = {
            natural_scroll = false,
            scroll_factor = 0.33,
        },
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
    },
    general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 1,
        col = {
            active_border = "rgb(33ccff)",
            inactive_border = "rgb(595959)",
        },
        layout = "dwindle",
    },
    decoration = {
        blur = {
            enabled = false,
        },
        rounding = 0,
        shadow = {
            enabled = false,
        },
    },
    animations = {
        enabled = false,
    },
    dwindle = {
        -- pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true, -- you probably want this
    },
    master = {
        new_status = "master",
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
    -- “no gaps when only”
    -- Main modifier
    -- Main binds
    -- bind = $mainMod, J, togglesplit, # dwindle
    -- Move focus
    -- Switch workspaces
    -- Switch to monitor
    -- Move active window to a workspace
    -- Move active workspace to a monitor
    -- Scroll through existing workspaces
    -- Move/resize windows
    -- Move windows
    -- Resize window
    -- Media
})

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("dunst")
    hl.exec_cmd("sleep 2 && /usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("sleep 2 && nextcloud --background")
    hl.exec_cmd("sleep 2 && wlsunset -l 48.21 -L 16.36")
    hl.exec_cmd("sleep 2 && keepassxc")
    hl.exec_cmd("sleep 2 && blueman-applet")
end)

